### ISSUE TITLE
Saving gzip in joomla 4 not working

### ISSUE THREAD

**Issue by ValentinAhrens** [tbela99/gzip#146] opened 2021-08-23 09:48 UTC
I install Gzip in joomla 4 and try to activate it but it did not work.
What can I do?

**Comment by tbela99** [comment] 2021-08-23 13:01
Hi, I fixed it here already https://github.com/tbela99/gzip/commit/15d3e1f5e18a561abbd63652dc05e77b69d056ec
It will be fixed in the next release, I do not have any date yet
You can manually edit the language file to fix it like in the commit mentioned above.
thanks

**Comment by ValentinAhrens** [comment] 2021-08-23 13:22
Thanks, but the language file is not installed.

**Comment by tbela99** [comment] 2021-08-23 13:38
I will create a new release which address only that issue

**Comment by tbela99** [comment] 2021-08-23 14:09
duplicate of #144

**Comment by tbela99** [comment] 2021-09-08 08:02
can you test this branch and let me know if your issue is fixed?
https://github.com/tbela99/gzip/tree/joomla4_compat

this should address Joomla 4 compatibility issues

**Comment by tbela99** [comment] 2021-09-08 08:02
thanks

**Comment by tbela99** [comment] 2021-09-08 08:14
should be fixed already.

**Closed by tbela99** 2021-09-08 08:14 UTC
Labels: duplicate
