### ISSUE TITLE
Can't install the plugin

### ISSUE THREAD

**Issue by ptest8794** [tbela99/gzip#7] opened 2018-05-29 20:39 UTC
Hi 

i would to try gzip but unfortunately i can't install because have the following error
JInstaller: :Install: the file not exists  /home/mywebsite/tmp/install_5b0db6aa24281/gzip-2.3/worker/css

Can you help me please?

**Comment by tbela99** [comment] 2018-05-30 00:50
Hello, 

Thanks for reporting that issue. I will fix it.
I am working on a release in this branch  that should solve your problem. The work is not finalized yet

https://github.com/tbela99/gzip/tree/Next

**Comment by tbela99** [comment] 2018-05-30 03:30
You should be able to install and use it from this branch https://github.com/tbela99/gzip/tree/Next
Please let me know if you have any issue.

Thanks

**Comment by tbela99** [comment] 2018-06-03 22:06
The issue is fixed in the new release. Please try again

**Closed by tbela99** 2018-06-03 22:06 UTC
