### ISSUE TITLE
500 err , when enabled "Convert to Webp or Avif"

### ISSUE THREAD

**Issue by aminweb2** [tbela99/gzip#164] opened 2022-04-06 09:01 UTC
hi @tbela99 
when Enabled "Convert to Webp or Avif" in Image tab. website get 500 Error. in error report : 
`Fatal error: Paletter image not supported by webp in /var/www/vhosts/site/test.com/plugins/system/gzip/helpers/Images.php on line 367 `
https://github.com/tbela99/gzip/blob/e17586a97e161e28568f83fa3cb19ed029ace44a/helpers/Images.php#L367
can you help me to fix it? thanks

I used php8.1 support webp (not support Avif)

**Comment by tbela99** [comment] 2022-04-06 12:29
As suggested by the error message, the problem comes from the provided image.
I will push an update to prevent the fatal error from getting in the way, but that will not address the problem with the image palette.

**Comment by aminweb2** [comment] 2022-04-06 12:47
i think this happen when generate webp for GIF images.

**Comment by tbela99** [comment] 2022-04-06 13:24
can you provide more details in a separate issue (File name and line number at least please.
Thanks

**Comment by aminweb2** [comment] 2022-04-06 14:05
i do not underestand exactly what you need. but i provide live website url:
https://test.atlantomed.eu/it/

**Comment by aminweb2** [comment] 2022-04-06 15:44
>  I will push an update to prevent the fatal error from getting in the way, but that will not address the problem with the image palette.
@tbela99 can you will do today?

**Comment by tbela99** [comment] 2022-04-06 15:46
maybe, let's say tomorrow

**Comment by aminweb2** [comment] 2022-04-06 15:52
so about problem CSS ?

**Comment by tbela99** [comment] 2022-04-06 15:53
I need you to provide more details like you did with this issue. I need the file name and line unmber at least

**Comment by aminweb2** [comment] 2022-04-06 16:04
in joomla log file (everything.php) :

`2022-04-06T14:52:23+00:00	CRITICAL 176.88.134.41	error	Uncaught Throwable of type Joomla\CMS\Router\Exception\RouteNotFoundException thrown with message "Pagina non trovata". Stack trace: #0 [ROOT]/libraries/src/Application/CMSApplication.php(1069): Joomla\CMS\Router\Router->parse(Object(Joomla\CMS\Uri\Uri), true)
#1 [ROOT]/libraries/src/Application/SiteApplication.php(820): Joomla\CMS\Application\CMSApplication->route()
#2 [ROOT]/libraries/src/Application/SiteApplication.php(228): Joomla\CMS\Application\SiteApplication->route()
#3 [ROOT]/libraries/src/Application/CMSApplication.php(278): Joomla\CMS\Application\SiteApplication->doExecute()
#4 [ROOT]/includes/app.php(63): Joomla\CMS\Application\CMSApplication->execute()
#5 [ROOT]/index.php(32): require_once('/var/www/vhosts...')
#6 {main}`

**Comment by aminweb2** [comment] 2022-04-06 16:57
about Convert webp log:

`
 Warning: imagecreatefromwebp(): gd-webp cannot get webp info in /var/www/vhosts/site.eu/test.site.eu/plugins/system/gzip/lib/Image/Image.php on line 101

Warning: imagesx() expects parameter 1 to be resource, null given in /var/www/vhosts/site.eu/test.site.eu/plugins/system/gzip/lib/Potracio/Potracio.php on line 180

Warning: imagesy() expects parameter 1 to be resource, null given in /var/www/vhosts/site.eu/test.site.eu/plugins/system/gzip/lib/Potracio/Potracio.php on line 181

Notice: Uninitialized string offset: 4 in /var/www/vhosts/site.eu/test.site.eu/plugins/system/gzip/helpers/Images.php on line 495

 Warning: Division by zero in /var/www/vhosts/site.eu/test.site.eu/plugins/system/gzip/lib/Image/Image.php on line 334

 Warning: imagesx() expects parameter 1 to be resource, null given in /var/www/vhosts/site.eu/test.site.eu/plugins/system/gzip/lib/Image/Image.php on line 312

 Warning: imagecopyresampled() expects parameter 1 to be resource, null given in /var/www/vhosts/site.eu/test.site.eu/plugins/system/gzip/lib/Image/Image.php on line 655

 Warning: imagecreatetruecolor() expects parameter 2 to be int, float given in /var/www/vhosts/site.eu/test.site.eu/plugins/system/gzip/lib/Image/Image.php on line 649

 Warning: imagesy() expects parameter 1 to be resource, null given in /var/www/vhosts/site.eu/test.site.eu/plugins/system/gzip/lib/Image/Image.php on line 313
`

**Comment by tbela99** [comment] 2022-04-06 17:03
I guess you image is corrupted in some way. I will fix that as well
Thanks

**Comment by tbela99** [comment] 2022-04-07 02:31
can you try this and let me know if your problems are solved? https://github.com/tbela99/gzip/archive/refs/heads/v.next.zip

**Comment by aminweb2** [comment] 2022-04-08 07:15
yes, problem solved.thank you
just have an question:
how exclude an url for effect gzip plugin?
P.S:when i enabled javascript process, crash my google map!

**Comment by tbela99** [comment] 2022-04-08 08:04
you can tell the plugin to ignore specific javascript and css. check the documentation here https://tbela99.github.io/gzip/#/./javascript?id=process-javascript

https://tbela99.github.io/gzip/#/./css?id=parse-critical-css

**Comment by tbela99** [comment] 2022-04-08 08:14
more generally, I see that you use speedcache. I think that it is redundant, as you can already manage css with this plugin.

**Comment by tbela99** [comment] 2022-04-08 08:20
If your problem is fixed, can you close this issue?
thanks!

**Comment by aminweb2** [comment] 2022-04-08 08:31
in Speedcache i used just " Group CSS " and " Group JS" .  if disable it , and then enabled just " Process CSS " --> make bad score in LCP and CLS . do you have any idea?

**Comment by tbela99** [comment] 2022-04-08 08:36
You already have it covered with merge Javascript and merge CSS options:

- merge javascript https://tbela99.github.io/gzip/#/./javascript?id=merge-javascript
- merge CSS https://tbela99.github.io/gzip/#/./css?id=merge-css

**Comment by aminweb2** [comment] 2022-04-09 08:31
@tbela99 i cannot achieve good results. :( 
can you help me? please. if ok for you, i will send admin access via email. please help me.
this is my email: am.ebrahimzadeh@gmail.com

**Comment by tbela99** [comment] 2022-04-09 08:50
I would rather have a backup that I can test locally. You can remove sensitive data before. You can send the link here and delete the message immediately

**Comment by aminweb2** [comment] 2022-04-09 09:04
http://test.atlantomed.eu/site-akeeba.zip 

when i disabled Gzip plugin (and all other extension for speed) i achieved in mobile 85% and desktop 97% (i attached image)
but when enabled gzip plugin , reduce my score in google pagespeed. please self try. i need will achieve upper 90% in mobile like as desktop.

https://prnt.sc/9kdq1-iBZYWn
https://prnt.sc/uBMGmo2fF6lk

THANKFUL @tbela99

**Comment by aminweb2** [comment] 2022-04-09 09:18
Were you able to download?

**Comment by tbela99** [comment] 2022-04-09 09:52
I meant you create the archive and share the link. I did not see any link

**Comment by aminweb2** [comment] 2022-04-09 10:14
i did, but delete immediately message 
https://test.atlantomed.eu/site-akeeba.zip
please after downloald let me know

**Comment by aminweb2** [comment] 2022-04-09 10:17
Note: when i disabled Gzip plugin i achieved 85% in mobile and 97% in desktop on google pagespeed,(i attached screen)
but when enabled Gzip plugin, it is down my score in google page speed. i want achieved upper 90% in mobile.

https://prnt.sc/9kdq1-iBZYWn
https://prnt.sc/uBMGmo2fF6lk

Thankful

**Comment by aminweb2** [comment] 2022-04-09 10:39
did you download?

**Comment by aminweb2** [comment] 2022-04-09 10:57
i did delete link message

**Comment by tbela99** [comment] 2022-04-09 19:13
I downloaded it. you can delete the archive.
I will test it as soon as I can
Thanks

**Comment by aminweb2** [comment] 2022-04-11 09:28
can you checked? please let me know. thank you

**Comment by tbela99** [comment] 2022-04-11 22:38
I will have time to work on that during the weekend. Now I am a little bit busy.
Thanks

**Comment by tbela99** [comment] 2022-04-11 22:49
your backup does not contain any database, it will not be possible for me to reproduce the issue. can you provide it please?
You don't need to provide the credentials. I will change them directly in my local setup.
Thanks

**Comment by tbela99** [comment] 2022-04-19 13:48
still working on this issue. I used akeeba to install from the backup. the site was not loading properly, probably because of a missing .htaccess.

**Comment by tbela99** [comment] 2022-04-21 00:20
1. after an investigation I found that you are using JCH Optimizer. Using both plugins leads to some kind of corruption that will cause css and js files to fail to load, hence the partially loaded page. disabling JCH fixed that problem. As a rule, you should not mix multiple optimization plugins
2. GIF files are not converted, probably because they are less than 800px width. I think this is probably an issue as I would expect images to be converted regardless their size

I noticed that you use animated GIF, I am not sure whether the conversion will preserve the animation. I will probably add a feature to enable conversion for individual file types. 

were you expecting GIF images to be converted?

**Comment by tbela99** [comment] 2022-05-06 09:48
I cannot reproduce the issue. I guess, it probably happened because many extensions were trying to do the same thing.

**Comment by tbela99** [comment] 2022-05-28 13:45
Hi, I just pushed an update to the v.next branch. It addresses a lot of issues.
You setup had caching enabled and some manual HTTP redirection when an exception occured, which made it a bit hard to understand why things did not work as expected.
I also solved another issue where the google hosted fonts were not downloaded.
I will run few more tests and published a new release in the next week or two.

Thanks

**Comment by aminweb2** [comment] 2022-05-28 14:02
thanks

**Comment by tbela99** [comment] 2022-06-01 23:23
Hello,

I have pushed a new update. I have fixed few bugs again and fixed some performance issues. I consistently achieve a score of 97 on desktop/mobile with pagespeed test and the default Joomla install.

Can you try it out and let me know? if this works for you, I will make a last code review before pushing the new version

![image](https://user-images.githubusercontent.com/58517/171517139-6b33edc5-27ec-494e-9ec6-b635a68cb2ee.png)

Thanks for your patience again :)

**Comment by tbela99** [comment] 2022-06-17 14:13
still working on it. I am addressing a performance regression. it should be good to go after that

**Comment by tbela99** [comment] 2022-07-02 02:50
fixed!

Thank you for your contribution.

**Closed by tbela99** 2022-07-02 02:50 UTC
